
export const text=(s,c=200,h={})=>new Response(s,{status:c,headers:{"content-type":"text/plain; charset=utf-8",...h}});
export const json=(o,c=200,h={})=>new Response(JSON.stringify(o),{status:c,headers:{"content-type":"application/json; charset=utf-8",...h}});
export const html=(s,c=200,h={})=>new Response(s,{status:c,headers:{"content-type":"text/html; charset=utf-8",...h}});

const enc=new TextEncoder();
function b64url(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
export async function signJWT(payload, secret){const header={alg:"HS256",typ:"JWT"};const seg=o=>btoa(JSON.stringify(o)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const data=seg(header)+"."+seg(payload);const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(data));return data+"."+b64url(sig)}
export async function verifyJWT(token, secret){const p=String(token||'').split('.');if(p.length!==3)return null;const[h,b,s]=p;try{const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["verify"]);const ok=await crypto.subtle.verify("HMAC",key,Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),enc.encode(h+"."+b));if(!ok)return null;return JSON.parse(atob(b.replace(/-/g,'+').replace(/_/g,'/')))}catch(e){return null}}

export async function splynxFetch(env, path, opt={}){const base=(env.SPLYNX_URL||'').replace(/\/$/,'');const headers={Authorization:env.AUTH_HEADER||'', 'Content-Type':'application/json'};const r=await fetch(base+path,{...opt,headers});const t=await r.text();let j=null;try{j=JSON.parse(t)}catch{}return {ok:r.ok,status:r.status,json:j,text:t}}

export async function verifyTurnstile(env, token, ip){try{const r=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:new URLSearchParams({secret:env.TURNSTILE_SECRET_KEY||"",response:token||"",remoteip:ip||""}),headers:{"content-type":"application/x-www-form-urlencoded"}});const j=await r.json();return !!j.success}catch(e){return false}}
export async function requireTurnstile(req, env){const ip=req.headers.get('CF-Connecting-IP')||'';const hdr=(req.headers.get('cf-turnstile-token')||'').trim();let token=hdr;if(!token&&req.method==="POST"){try{const ct=req.headers.get("content-type")||"";if(ct.includes("application/x-www-form-urlencoded")||ct.includes("multipart/form-data")){const f=await req.formData().catch(()=>null);if(f){token=String(f.get('cf_turnstile_token')||f.get('cf-turnstile-token')||'');}}}catch(e){}}if(!(await verifyTurnstile(env, token, ip)))return false;return true}

export async function sendWhatsApp(env,to,body){try{const url=`https://graph.facebook.com/v15.0/${env.PHONE_NUMBER_ID}/messages`;const r=await fetch(url,{method:"POST",headers:{"Authorization":`Bearer ${env.WHATSAPP_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:String(to).replace(/\D+/g,''),type:"text",text:{body}})});return {ok:r.ok,status:r.status,body:await r.text()}}catch(e){return {ok:false,error:String(e)}}}
export async function sendWhatsAppTemplate(env,to,template,lang,components){try{const url=`https://graph.facebook.com/v15.0/${env.PHONE_NUMBER_ID}/messages`;const payload={messaging_product:"whatsapp",to:String(to).replace(/\D+/g,''),type:"template",template:{name:template,language:{code:lang||env.WA_LANG||"en"},components:components||[]}};const r=await fetch(url,{method:"POST",headers:{"Authorization":`Bearer ${env.WHATSAPP_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const t=await r.text();let j=null;try{j=JSON.parse(t)}catch{}return {ok:r.ok,status:r.status,body:j||t}}catch(e){return {ok:false,error:String(e)}}}
